version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.1.0
  - dependency-name: nuxt
    versions:
    - 2.15.0
    - 2.15.2
    - 2.15.3
  - dependency-name: pug
    versions:
    - 3.0.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: "@nuxtjs/axios"
    versions:
    - 5.13.0
  - dependency-name: "@nuxtjs/eslint-config-typescript"
    versions:
    - 5.0.0
