root: true
env:
  browser: true
  node: true
extends:
  - '@nuxtjs/eslint-config-typescript'
  - prettier
  - prettier/vue
  - plugin:prettier/recommended
  - plugin:nuxt/recommended
plugins:
  - filenames
rules:
  filenames/match-regex:
    - error
    - '^[.-0-9a-z]+$'
