root: true
env:
  browser: true
  node: true
extends:
  - '@nuxtjs/eslint-config-typescript'
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:filenames-simple/recommended-vue
  - prettier
  - plugin:prettier/recommended
  - plugin:nuxt/recommended
settings:
  import/resolver:
    nuxt:
      extensions:
        - .vue
        - .ts
        - .js
        - .json
overrides:
  - files:
      - layouts/*.vue
    plugins:
      - filenames-simple
    rules:
      filenames-simple/naming-convention:
        - error
        - rule: kebab-case
