name: Build Nuxt.js for test

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
      - run: yarn install --frozen-lockfile

      - run: yarn run lint
      - run: yarn run build
