name: Deploy to github pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x
          cache: yarn
      - run: yarn install --frozen-lockfile

      - run: yarn run generate

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: www.epaew.net
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./dist
